apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: "hubble-middleware-custom"
rules:
  - apiGroups:
      - "user.openshift.io"
    resources:
      - projects
    verbs:
      - get
      - list
      - watch
      - impersonate
  - apiGroups:
      - networking.k8s.io
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
      - impersonate
  - apiGroups:
      - ""
    resources:
      - componentstatuses
      - endpoints
      - namespaces
      - nodes
      - pods
      - services
    verbs:
      - get
      - list
      - watch
      - impersonate
  - apiGroups:
      - ""
    resources:
      - users
      - groups
    verbs:
      - impersonate
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
      - impersonate
  - apiGroups:
      - cilium.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - impersonate
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: hubble-middleware
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: hubble-middleware-custom
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hubble-middleware-custom
subjects:
  - kind: ServiceAccount
    name: hubble-middleware
    namespace: kube-system
